/**
 * Compliance Package PDF Template
 *
 * HTML template for generating compliance package PDFs.
 * Includes 7 sections as per Part 5 of the design guide:
 * 1. Cover Page
 * 2. Equipment Summary
 * 3. Work Order Details
 * 4. Meter Reading History
 * 5. Downtime Summary
 * 6. Audit Trail Summary
 * 7. Certification
 *
 * @module services/pdf/templates/compliance-package-template
 */

import type Asset from '@/database/models/Asset';
import type WorkOrder from '@/database/models/WorkOrder';
import type MeterReading from '@/database/models/MeterReading';
import { pdfStyles } from './styles';
import {
  formatDate,
  formatTime,
  formatDuration,
  formatTimestamp,
} from '../utils/image-utils';
import {
  type CompliancePackageData,
  calculateAssetDowntime,
  calculateAllAssetDowntime,
  calculateAuditSummary,
  calculatePackageHash,
  getTruncatedPackageHash,
  countAssetWorkOrders,
  getLatestMeterReading,
  formatDateRange,
  formatHours,
} from '../utils/compliance-utils';

// Re-export for external use
export type { CompliancePackageData };

/**
 * Status display configuration
 */
const STATUS_CONFIG: Record<string, { label: string; class: string }> = {
  operational: { label: 'Operational', class: 'badge-operational' },
  down: { label: 'Down', class: 'badge-down' },
  limited: { label: 'Limited', class: 'badge-limited' },
};

/**
 * Work order status configuration
 */
const WO_STATUS_CONFIG: Record<string, { label: string; class: string }> = {
  completed: { label: 'Completed', class: 'badge-completed' },
  in_progress: { label: 'In Progress', class: 'badge-in-progress' },
  open: { label: 'Open', class: 'badge-open' },
};

/**
 * Priority display configuration
 */
const PRIORITY_CONFIG: Record<string, { label: string; class: string }> = {
  emergency: { label: 'Emergency', class: 'badge-emergency' },
  high: { label: 'High', class: 'badge-high' },
  medium: { label: 'Medium', class: 'badge-medium' },
  low: { label: 'Low', class: 'badge-low' },
};

/**
 * Failure type labels
 */
const FAILURE_TYPE_LABELS: Record<string, string> = {
  none: 'None',
  wore_out: 'Wore Out',
  broke: 'Broke',
  unknown: 'Unknown',
};

/**
 * Escape HTML special characters
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
    .replace(/\n/g, '<br>');
}

// ============================================================================
// SECTION 1: Cover Page
// ============================================================================

/**
 * Generate HTML for the cover page section
 */
function generateCoverPage(
  data: CompliancePackageData,
  packageHash: string
): string {
  const dateRangeText = formatDateRange(data.dateRange);
  const generatedText = `${formatDate(data.generatedAt.getTime())} at ${formatTime(data.generatedAt.getTime())}`;

  return `
    <div class="cover-page">
      <div class="cover-title">Compliance Package</div>
      <div class="cover-subtitle">Maintenance Records Report</div>

      <div class="cover-info" style="margin-top: 48px;">
        <strong>${escapeHtml(data.companyName)}</strong>
      </div>
      <div class="cover-info">${escapeHtml(data.siteName)}</div>

      <div class="cover-date-range">
        ${dateRangeText}
      </div>

      <div class="toc">
        <div class="toc-title">Contents</div>
        <div class="toc-item">
          <span class="toc-section">1. Equipment Summary</span>
          <span class="toc-page">${data.assets.length} assets</span>
        </div>
        <div class="toc-item">
          <span class="toc-section">2. Work Order Details</span>
          <span class="toc-page">${data.workOrders.length} work orders</span>
        </div>
        <div class="toc-item">
          <span class="toc-section">3. Meter Reading History</span>
          <span class="toc-page">${data.meterReadings.length} readings</span>
        </div>
        <div class="toc-item">
          <span class="toc-section">4. Downtime Summary</span>
          <span class="toc-page">Analysis</span>
        </div>
        <div class="toc-item">
          <span class="toc-section">5. Audit Trail Summary</span>
          <span class="toc-page">Statistics</span>
        </div>
        <div class="toc-item">
          <span class="toc-section">6. Certification</span>
          <span class="toc-page">Verification</span>
        </div>
      </div>

      <div class="cover-generated">
        Generated by ${escapeHtml(data.generatedBy)}<br>
        ${generatedText}
      </div>

      <div class="cover-hash">
        Package Hash: ${getTruncatedPackageHash(packageHash)}
      </div>
    </div>
  `;
}

// ============================================================================
// SECTION 2: Equipment Summary
// ============================================================================

/**
 * Generate HTML for a single equipment card
 */
function generateEquipmentCard(
  asset: Asset,
  workOrders: WorkOrder[],
  meterReadings: MeterReading[]
): string {
  const statusConfig = STATUS_CONFIG[asset.status] ?? { label: 'Operational', class: 'badge-operational' };
  const woCount = countAssetWorkOrders(asset.id, workOrders);
  const latestMeter = getLatestMeterReading(asset.id, meterReadings);
  const downtime = calculateAssetDowntime(asset.id, workOrders);

  return `
    <div class="equipment-card">
      <div class="equipment-header">
        <div>
          <div class="equipment-name">${escapeHtml(asset.name)}</div>
          <div class="equipment-number">${asset.assetNumber}</div>
        </div>
        <span class="badge ${statusConfig.class}">${statusConfig.label}</span>
      </div>

      <div class="info-grid" style="gap: 4px 16px;">
        <div class="info-row">
          <span class="info-label">Category</span>
          <span class="info-value">${asset.category}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Location</span>
          <span class="info-value">${asset.locationDescription || '--'}</span>
        </div>
      </div>

      <div class="equipment-stats">
        <div class="equipment-stat">
          <div class="equipment-stat-value">${woCount}</div>
          <div class="equipment-stat-label">Work Orders</div>
        </div>
        <div class="equipment-stat">
          <div class="equipment-stat-value">${formatHours(downtime.totalHours)}</div>
          <div class="equipment-stat-label">Downtime</div>
        </div>
        <div class="equipment-stat">
          <div class="equipment-stat-value">${latestMeter !== null ? latestMeter.toLocaleString() : '--'}</div>
          <div class="equipment-stat-label">${asset.meterType || 'Meter'}</div>
        </div>
        <div class="equipment-stat">
          <div class="equipment-stat-value">${downtime.eventCount}</div>
          <div class="equipment-stat-label">Events</div>
        </div>
      </div>
    </div>
  `;
}

/**
 * Generate HTML for the equipment summary section
 */
function generateEquipmentSummary(
  assets: Asset[],
  workOrders: WorkOrder[],
  meterReadings: MeterReading[]
): string {
  if (assets.length === 0) {
    return `
      <div class="page-break-before">
        <div class="section-header">Section 1: Equipment Summary</div>
        <div class="description-text" style="text-align: center; color: #999;">
          No assets in scope
        </div>
      </div>
    `;
  }

  // Sort assets by name
  const sortedAssets = [...assets].sort((a, b) => a.name.localeCompare(b.name));

  return `
    <div class="page-break-before">
      <div class="section-header">Section 1: Equipment Summary</div>
      <p style="margin-bottom: 16px; color: #666;">
        ${assets.length} assets included in this compliance package.
      </p>
      ${sortedAssets.map(asset =>
        generateEquipmentCard(asset, workOrders, meterReadings)
      ).join('')}
    </div>
  `;
}

// ============================================================================
// SECTION 3: Work Order Details
// ============================================================================

/**
 * Generate HTML for a single work order card
 */
function generateWorkOrderCard(
  workOrder: WorkOrder,
  asset: Asset | undefined
): string {
  const statusConfig = WO_STATUS_CONFIG[workOrder.status] ?? { label: 'Open', class: 'badge-open' };
  const priorityConfig = PRIORITY_CONFIG[workOrder.priority] ?? { label: 'Medium', class: 'badge-medium' };

  return `
    <div class="wo-card">
      <div class="wo-card-header">
        <span class="wo-card-number">${workOrder.woNumber}</span>
        <div>
          <span class="badge ${priorityConfig.class}" style="font-size: 10px;">${priorityConfig.label}</span>
          <span class="badge ${statusConfig.class}" style="font-size: 10px; margin-left: 4px;">${statusConfig.label}</span>
        </div>
      </div>

      <div class="wo-card-body">
        <div class="wo-card-title">${escapeHtml(workOrder.title)}</div>

        <div class="wo-card-grid">
          <div class="info-row">
            <span class="info-label">Asset</span>
            <span class="info-value">${asset ? asset.assetNumber : '--'}</span>
          </div>
          <div class="info-row">
            <span class="info-label">Failure Type</span>
            <span class="info-value">${FAILURE_TYPE_LABELS[workOrder.failureType || 'none']}</span>
          </div>
          <div class="info-row">
            <span class="info-label">Started</span>
            <span class="info-value">${workOrder.startedAt ? `${formatDate(workOrder.startedAt)} ${formatTime(workOrder.startedAt)}` : '--'}</span>
          </div>
          <div class="info-row">
            <span class="info-label">Completed</span>
            <span class="info-value">${workOrder.completedAt ? `${formatDate(workOrder.completedAt)} ${formatTime(workOrder.completedAt)}` : '--'}</span>
          </div>
          <div class="info-row">
            <span class="info-label">Time Spent</span>
            <span class="info-value">${formatDuration(workOrder.timeSpentMinutes)}</span>
          </div>
          <div class="info-row">
            <span class="info-label">Completed By</span>
            <span class="info-value">${workOrder.completedBy || '--'}</span>
          </div>
        </div>

        ${workOrder.description ? `
          <div class="wo-card-notes">
            <strong>Description:</strong><br>
            ${escapeHtml(workOrder.description)}
          </div>
        ` : ''}

        ${workOrder.completionNotes ? `
          <div class="wo-card-notes">
            <strong>Work Performed:</strong><br>
            ${escapeHtml(workOrder.completionNotes)}
          </div>
        ` : ''}

        ${workOrder.signatureHash ? `
          <div class="wo-signature-section">
            <div class="verification-title" style="font-size: 11px;">Signature Verification</div>
            <div style="font-size: 10px; color: #666;">
              ${workOrder.verificationCode ? `
                <div style="font-family: monospace; font-weight: 600; color: #1976D2; margin-bottom: 4px;">
                  ${workOrder.verificationCode}
                </div>
              ` : ''}
              <div>Signed by: ${workOrder.completedBy || 'Unknown'}</div>
              <div>Timestamp: ${formatTimestamp(workOrder.signatureTimestamp)}</div>
              <div class="verification-hash" style="margin-top: 4px; font-size: 9px; word-break: break-all;">
                SHA-256: ${workOrder.signatureHash}
              </div>
              ${workOrder.verificationCode ? `
                <div style="margin-top: 4px; font-style: italic; font-size: 9px;">
                  Verify: verify.example.com/${workOrder.verificationCode}
                </div>
              ` : ''}
            </div>
          </div>
        ` : ''}
      </div>
    </div>
  `;
}

/**
 * Generate HTML for the work order details section
 */
function generateWorkOrderDetails(
  workOrders: WorkOrder[],
  assets: Asset[]
): string {
  if (workOrders.length === 0) {
    return `
      <div class="page-break-before">
        <div class="section-header">Section 2: Work Order Details</div>
        <div class="description-text" style="text-align: center; color: #999;">
          No work orders in the selected date range
        </div>
      </div>
    `;
  }

  // Create asset lookup map
  const assetMap = new Map(assets.map(a => [a.id, a]));

  // Sort work orders by completion date (newest first) or creation date
  const sortedOrders = [...workOrders].sort((a, b) => {
    const dateA = a.completedAt || a.localUpdatedAt;
    const dateB = b.completedAt || b.localUpdatedAt;
    return dateB - dateA;
  });

  return `
    <div class="page-break-before">
      <div class="section-header">Section 2: Work Order Details</div>
      <p style="margin-bottom: 16px; color: #666;">
        ${workOrders.length} work orders in the selected date range.
      </p>
      ${sortedOrders.map(wo =>
        generateWorkOrderCard(wo, assetMap.get(wo.assetId))
      ).join('')}
    </div>
  `;
}

// ============================================================================
// SECTION 4: Meter Reading History
// ============================================================================

/**
 * Generate HTML for meter readings for a single asset
 */
function generateAssetMeterReadings(
  asset: Asset,
  meterReadings: MeterReading[]
): string {
  const assetReadings = meterReadings
    .filter(mr => mr.assetId === asset.id)
    .sort((a, b) => (b.readingDate || 0) - (a.readingDate || 0));

  if (assetReadings.length === 0) {
    return '';
  }

  return `
    <div class="equipment-card">
      <div class="equipment-header">
        <div>
          <div class="equipment-name">${escapeHtml(asset.name)}</div>
          <div class="equipment-number">${asset.assetNumber} - ${asset.meterType || 'Meter'}</div>
        </div>
        <span style="font-size: 12px; color: #666;">${assetReadings.length} readings</span>
      </div>

      <table style="margin-top: 12px;">
        <thead>
          <tr>
            <th>Date</th>
            <th>Reading</th>
            <th>Recorded By</th>
            <th>Flag</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          ${assetReadings.slice(0, 15).map((reading, index) => {
            const prevReading = assetReadings[index + 1];
            const change = prevReading
              ? reading.readingValue - prevReading.readingValue
              : 0;
            const isHighChange = prevReading && change > (prevReading.readingValue * 0.5);
            return `
              <tr>
                <td>${formatDate(reading.readingDate)}</td>
                <td><strong>${reading.readingValue.toLocaleString()}</strong> ${asset.meterUnit || ''}</td>
                <td>${reading.recordedBy || '--'}</td>
                <td>${isHighChange
                  ? '<span class="meter-flag meter-flag-high">High Change</span>'
                  : '<span class="meter-flag meter-flag-normal">Normal</span>'}</td>
                <td>${reading.notes || '--'}</td>
              </tr>
            `;
          }).join('')}
        </tbody>
      </table>
      ${assetReadings.length > 15 ? `
        <div style="text-align: center; padding: 8px; color: #666; font-style: italic; font-size: 11px;">
          Showing 15 of ${assetReadings.length} readings
        </div>
      ` : ''}
    </div>
  `;
}

/**
 * Generate HTML for the meter reading history section
 */
function generateMeterReadingHistory(
  assets: Asset[],
  meterReadings: MeterReading[]
): string {
  // Filter assets with meters
  const assetsWithMeters = assets.filter(a => a.meterType);

  if (assetsWithMeters.length === 0 || meterReadings.length === 0) {
    return `
      <div class="page-break-before">
        <div class="section-header">Section 3: Meter Reading History</div>
        <div class="description-text" style="text-align: center; color: #999;">
          No meter readings in the selected date range
        </div>
      </div>
    `;
  }

  return `
    <div class="page-break-before">
      <div class="section-header">Section 3: Meter Reading History</div>
      <p style="margin-bottom: 16px; color: #666;">
        ${meterReadings.length} meter readings across ${assetsWithMeters.length} assets.
      </p>
      ${assetsWithMeters.map(asset =>
        generateAssetMeterReadings(asset, meterReadings)
      ).join('')}
    </div>
  `;
}

// ============================================================================
// SECTION 5: Downtime Summary
// ============================================================================

/**
 * Generate HTML for the downtime summary section
 */
function generateDowntimeSummary(
  assets: Asset[],
  workOrders: WorkOrder[]
): string {
  const downtimeStats = calculateAllAssetDowntime(assets, workOrders);

  if (downtimeStats.length === 0) {
    return `
      <div class="page-break-before">
        <div class="section-header">Section 4: Downtime Summary</div>
        <div class="description-text" style="text-align: center; color: #999;">
          No downtime events recorded in the selected date range
        </div>
      </div>
    `;
  }

  // Calculate totals
  const totalHours = downtimeStats.reduce((sum, s) => sum + s.totalHours, 0);
  const totalEvents = downtimeStats.reduce((sum, s) => sum + s.eventCount, 0);
  const maxDowntime = Math.max(...downtimeStats.map(s => s.longestEventHours));

  // Create asset lookup map
  const assetMap = new Map(assets.map(a => [a.id, a]));

  return `
    <div class="page-break-before">
      <div class="section-header">Section 4: Downtime Summary</div>

      <div class="summary-box" style="margin-bottom: 24px;">
        <div class="summary-item">
          <div class="summary-value">${formatHours(totalHours)}</div>
          <div class="summary-label">Total Downtime</div>
        </div>
        <div class="summary-item">
          <div class="summary-value">${totalEvents}</div>
          <div class="summary-label">Total Events</div>
        </div>
        <div class="summary-item">
          <div class="summary-value">${formatHours(maxDowntime)}</div>
          <div class="summary-label">Longest Event</div>
        </div>
        <div class="summary-item">
          <div class="summary-value">${downtimeStats.length}</div>
          <div class="summary-label">Assets Affected</div>
        </div>
      </div>

      <table class="downtime-table">
        <thead>
          <tr>
            <th>Asset</th>
            <th>Total Downtime</th>
            <th># of Events</th>
            <th>Longest Event</th>
          </tr>
        </thead>
        <tbody>
          ${downtimeStats.map((stat, index) => {
            const asset = assetMap.get(stat.assetId);
            const isHighlight = index === 0;
            return `
              <tr class="${isHighlight ? 'downtime-highlight' : ''}">
                <td>${asset ? `${asset.name} (${asset.assetNumber})` : stat.assetId}</td>
                <td>${formatHours(stat.totalHours)}</td>
                <td>${stat.eventCount}</td>
                <td>${formatHours(stat.longestEventHours)}</td>
              </tr>
            `;
          }).join('')}
        </tbody>
      </table>
    </div>
  `;
}

// ============================================================================
// SECTION 6: Audit Trail Summary
// ============================================================================

/**
 * Generate HTML for the audit trail summary section
 */
function generateAuditTrailSummary(
  workOrders: WorkOrder[],
  meterReadings: MeterReading[]
): string {
  const audit = calculateAuditSummary(workOrders, meterReadings);

  return `
    <div class="page-break-before">
      <div class="section-header">Section 5: Audit Trail Summary</div>

      <div class="audit-summary-grid">
        <div class="audit-summary-item">
          <div class="audit-summary-value">${audit.workOrdersCreated}</div>
          <div class="audit-summary-label">Work Orders Created</div>
        </div>
        <div class="audit-summary-item">
          <div class="audit-summary-value">${audit.workOrdersCompleted}</div>
          <div class="audit-summary-label">Work Orders Completed</div>
        </div>
        <div class="audit-summary-item ${audit.workOrdersModifiedAfterCompletion > 0 ? 'audit-warning' : ''}">
          <div class="audit-summary-value">${audit.workOrdersModifiedAfterCompletion}</div>
          <div class="audit-summary-label">Modified After Completion</div>
        </div>
      </div>

      <div class="audit-summary-grid" style="margin-top: 16px;">
        <div class="audit-summary-item">
          <div class="audit-summary-value">${audit.meterReadingsRecorded}</div>
          <div class="audit-summary-label">Meter Readings</div>
        </div>
        <div class="audit-summary-item">
          <div class="audit-summary-value">${audit.signaturesCaptured}</div>
          <div class="audit-summary-label">Signatures Captured</div>
        </div>
        <div class="audit-summary-item">
          <div class="audit-summary-value">${audit.syncConflictsResolved}</div>
          <div class="audit-summary-label">Sync Conflicts Resolved</div>
        </div>
      </div>

      ${audit.syncConflictsEscalated > 0 ? `
        <div style="margin-top: 24px; padding: 16px; background: #FFF3E0; border-radius: 8px;">
          <div style="font-weight: 600; color: #E65100; margin-bottom: 8px;">
            Attention Required
          </div>
          <div style="font-size: 12px; color: #666;">
            ${audit.syncConflictsEscalated} work order(s) flagged for review due to
            quick completion without notes. Please verify these records.
          </div>
        </div>
      ` : ''}
    </div>
  `;
}

// ============================================================================
// SECTION 7: Certification
// ============================================================================

/**
 * Generate HTML for the certification section
 */
function generateCertification(
  data: CompliancePackageData,
  packageHash: string
): string {
  const generatedText = `${formatDate(data.generatedAt.getTime())} at ${formatTime(data.generatedAt.getTime())}`;

  return `
    <div class="page-break-before">
      <div class="section-header">Section 6: Certification</div>

      <div class="certification-section">
        <div class="certification-title">Certification</div>

        <div class="certification-text">
          This compliance package was generated from the QuarryCMMS database
          on ${generatedText} by ${escapeHtml(data.generatedBy)}.
          <br><br>
          The records contained herein are complete for the date range specified
          (${formatDateRange(data.dateRange)}) and have not been modified since
          their original creation, except where noted in the audit trail.
          <br><br>
          All signatures are cryptographically verifiable using the verification
          codes provided. Each signature hash is generated from the signature image,
          completion timestamp, and work order identifier.
        </div>

        <div class="certification-hash">
          Package Integrity Hash: ${packageHash}
        </div>

        <div class="certification-footer">
          For verification assistance: support@example.com
        </div>
      </div>
    </div>
  `;
}

// ============================================================================
// Main Export
// ============================================================================

/**
 * Generate complete HTML for a compliance package PDF
 *
 * @param data - Compliance package data
 * @returns Promise resolving to complete HTML string for PDF generation
 */
export async function generateCompliancePackageHtml(data: CompliancePackageData): Promise<string> {
  // Calculate package hash first (used in cover and certification)
  // Now uses proper SHA-256 via expo-crypto
  const packageHash = await calculatePackageHash(data);

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Compliance Package - ${data.siteName} - ${formatDateRange(data.dateRange)}</title>
      <style>${pdfStyles}</style>
    </head>
    <body>
      ${generateCoverPage(data, packageHash)}
      ${generateEquipmentSummary(data.assets, data.workOrders, data.meterReadings)}
      ${generateWorkOrderDetails(data.workOrders, data.assets)}
      ${generateMeterReadingHistory(data.assets, data.meterReadings)}
      ${generateDowntimeSummary(data.assets, data.workOrders)}
      ${generateAuditTrailSummary(data.workOrders, data.meterReadings)}
      ${generateCertification(data, packageHash)}
    </body>
    </html>
  `;
}

export default generateCompliancePackageHtml;
